# Generated by Django 2.2.28 on 2024-11-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id_attraction', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('etat', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermée', 'Fermée'), ('maintenance', 'En maintenance')], max_length=20)),
                ('capacite', models.PositiveIntegerField(default=0)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
    ]
