# Generated by Django 2.2.28 on 2024-11-15 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='etat',
            field=models.CharField(choices=[('ouverte', 'Ouverte'), ('fermée', 'Fermée')], max_length=20),
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id_visiteur', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('etat', models.CharField(choices=[('fatigué', 'Fatigué'), ('prêt', 'Prêt'), ('affamé', 'Affamé'), ('enjoué', 'Enjoué')], max_length=20)),
                ('photo', models.CharField(max_length=200)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Attraction')),
            ],
        ),
    ]
